### PR TITLE
#68 benchmarks page

### LINKED ISSUE #68: Benchmarks page (single page)
Broken out from umbrella issue.

Lists all benchmarks, possibly their question sets as well

### PR DESCRIPTION
**Pull request by stouffers**
Closes #68

### CODE REVIEW

File: gui/src/ts/components/benchmark/BenchmarkPage.tsx [hunk 1]
```diff
@@ -52,6 +52,11 @@ export const BenchmarkPage: React.FunctionComponent = () => {
   return (
     <Frame>
       <Grid container direction="column" spacing={6}>
+        <Grid item>
+          <Link to={Hrefs.benchmarks} data-cy="benchmarks-link">
```
Comment (gordom6) [inline gui/src/ts/components/benchmark/BenchmarkPage.tsx:56]: Joshua is working on a "BenchmarkFrame" that will have breadcrumbs and other common code for the benchmark page hierarchy, so this bespoke stuff will go away.

File: gui/src/ts/components/benchmark/BenchmarksPage.tsx [hunk 2]
```diff
@@ -1,10 +1,53 @@
...
     <Frame>
-      <h1>Benchmarks page</h1>
+      <Grid container direction="column" spacing={1}>
+        <Grid item>
+          <Typography variant="h4">Benchmarks</Typography>
+        </Grid>
+        <Grid item>
+          <List>
+            {data.benchmarks.map((bm) => (
+              <ListItem key={bm.id}>
```
Comment (gordom6) [inline gui/src/ts/components/benchmark/BenchmarksPage.tsx:39]: I made my pages show tables even though I only have a name column, because there will eventually be other metadata here, like the number of submissions, for example. Fine to leave for now.

File: test/integration/cypress/integration/BenchmarkPage.spec.ts [hunk 3]
```diff
@@ -35,4 +36,10 @@ context("Benchmark page", () => {
         });
     });
   });
+
+  it("should link back to benchmarks page", () => {
```
Comment (gordom6) [inline test/integration/cypress/integration/BenchmarkPage.spec.ts:40]: This will go away and we'll put the breadcrumb testing at the deepest level of the benchmark page hierarchy.

File: gui/src/ts/components/benchmark/BenchmarkPage.tsx (hunk 1 above)
Comment (stouffers) [reply gui/src/ts/components/benchmark/BenchmarkPage.tsx:56]: nice
